language: php

php:
  - 7.2
  - 7.3

addons:
  mariadb: '10.4'

services:
  - redis-server

before_install:
  - sudo service redis-server start --bind 127.0.0.1
  - before_script: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install

script:
  - composer run tu

after_success:
  - echo "test after success"
