language: php

php:
  - 7.3

services:
  - redis-server

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer install
  - composer run cs
  - composer run tu

after_success:
  - travis_retry php vendor/bin/php-coveralls -v --exclude-no-stmt
