language: php

php:
  - 7.2
  - 7.3

addons:
  mariadb: '10.4'

services:
  - redis-server

install:
  - composer install

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer run tu

after_success:
  - echo "test after success"
